- README.md
- ogr/services/abstract.py
- ogr/services/github.py
- ogr/services/gitlab.py
- ogr/services/our_pagure.py
- ogr/services/pagure.py
- tests/integration/our_pagure.py
- tests/integration/pagure.py
- tests/unit/our_pagure.py
- tests/unit/pagure.py
- Add tests for Pagure and OurPagure.
- Update the API and Pagure implementation.
> Update API and Pagure

- .git_archival.txt
- .gitattributes
- LICENSE
- Makefile
- ogr/__init__.py
- recipe.yaml
- setup.cfg
- setup.py
- add MIT license
- use setuptools-scm
- add Makefile target for image and pypi-checking
> Introduce packaging

- ogr/services/abstract.py
- ogr/services/pagure.py
- ogr/utils.py
- tests/integration/pagure.py
- tests/unit/utils.py
- Add method for filtering comments in pr.
- Fix pr_info and pr_comment content.
- TODO:
> Pr info and comments

- ogr/abstract.py
- ogr/services/github.py
- ogr/services/our_pagure.py
- ogr/services/pagure.py
- tests/integration/test_github.py
- tests/integration/test_pagure.py
- Rework github implementation.
- Add tests for github.
- Add API for file content.
- Correct Pagure tests.
> github support

- README.md
- setup.cfg
> Fix the name meaning and prepare for the move to packit-service

- ogr/abstract.py
- ogr/services/github.py
- ogr/services/pagure.py
- Remove future import for annotations => python3.6 compatibility.
Resolves #13
> Use strings for type annotations

- python-ogr.spec
Downstream commit: 48f9c4254f4eb328740129f902c9836105cdc86c
> Update from downstream branch 'master'

- ogr/services/github.py
Exsmple: https://github.com/dhodovsk/rsyslog/pull/1
> Implement adding PR comments

- ogr/services/github.py
- ogr/services/mock/github_mock.py
- ogr/services/mock/pagure_mock.py
- ogr/services/pagure.py
- tests/integration/test_github.py
- tests/integration/test_github_readonly.py
- tests/integration/test_pagure.py
Improve mocking, to be easily able mock `packit` via passing `persistent_storage` class variable
> improve mock of persistent objects

- .packit.yaml
- ogr/mock_core.py
\+ packit.yaml: add a link to docs
> dump() when store() is called

- ogr/mock_core.py
- ogr/services/github.py
- ogr/services/pagure.py
Rename @readonly to @if_readonly.
Fixes #56
> Rename readonly decorator

- ogr/abstract.py
- ogr/mock_core.py
- ogr/services/github.py
- ogr/services/pagure.py
- [pagure] Use empty dict as a default header.
> Fix pagure header without token

- ogr/__init__.py
- ogr/abstract.py
- ogr/constant.py
- ogr/exceptions.py
- ogr/mock_core.py
- ogr/services/__init__.py
- ogr/services/base.py
- ogr/services/github.py
- ogr/services/gitlab.py
- ogr/services/mock/__init__.py
- ogr/services/mock/github_mock.py
- ogr/services/mock/pagure_mock.py
- ogr/services/pagure.py
- ogr/utils.py
- Add MIT headers to code files.
> Add license headers

- ogr/services/github.py
- ogr/services/gitlab.py
- ogr/services/pagure.py
- Fix formating for __str__ methods.
- Changes requested to_str_method of classes. @shreyanshrs44
- Added instantiation-like syntax. @shreyanshrs44
- Added __str__ method to classes. @shreyanshrs44
- Added __str__ method to classes. @shreyanshrs44
Fixed version of #93
> Added __str__ method to classes. (new)

- ogr/abstract.py
- ogr/services/pagure.py
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_info.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_list.yaml
- tests/integration/test_pagure.py
Related to #80
This PR contains functionality for Pagure issues except for tagging issues. I had some problems with tagging, therefore, I'll create separated PR for it.
If I am right I have to set Pagure token for creating yaml test-files. We can manage that in private chat, then I'll add tests.
> creating/closing/commenting Pagure Issues

- ogr/services/github.py
> in get_file_content catch only 404

- ogr/mock_core.py
See https://github.com/packit-service/packit/pull/407
> Make PersistentObjectStorage.__init__() backwards compatible

- ogr/abstract.py
- ogr/services/github.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_releases.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_tag_from_nonexisting_tag_name.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_tag_from_tag_name.yaml
- tests/integration/test_github.py
> link to GitTag from Release added

- ogr/utils.py
> unused functions in utils.py removed

- ogr/services/github.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_create_release.yaml
- tests/integration/test_github.py
> method create release for github created

- .zuul.yaml
- Makefile
- pre-commit-pb.yaml
- recipe.yaml
EDIT (jpopelka): https://zuul-ci.org/docs/zuul/user/config.html#project
EDIT2 (jpopelka): http://post-office.corp.redhat.com/archives/user-cont/2019-July/msg00086.html
> add zuul config

- .packit.yaml
https://packit.dev/docs/configuration/#supported-jobs
> packit.yaml: propose_downstream: s/_/-/

- ogr/abstract.py
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
Add function `get_pr_commits` into `abstract.py`.
> Add get_pr_commits into abstract.py

- ogr/abstract.py
- ogr/services/github.py
- ogr/services/pagure.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.Releases.test_edit_release.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Releases.test_get_release.yaml
- tests/integration/test_github.py
> add method edit_release

- .zuul.yaml
- files/tasks/build-rpm-deps.yaml
- files/tasks/configure-git.yaml
- files/tasks/generic-dnf-requirements.yaml
- files/tasks/install-ogr.yaml
- files/tasks/python-compile-deps.yaml
- files/tasks/rpm-test-deps.yaml
- files/tasks/zuul-project-setup.yaml
- files/zuul-install-requirements-pip.yaml
- files/zuul-install-requirements-rpms.yaml
- files/zuul-tests.yaml
- Run zuul tests both on pip and rpm.
> Run zuul for pip and rpm

- ogr/__init__.py
- ogr/factory.py
- ogr/services/github.py
- ogr/services/gitlab.py
- ogr/services/pagure.py
- tests/unit/test_factory.py
- Add method for loading services from dictionary.
- Tests included.
Fixes: #159
> Loading services from dict

- ogr/abstract.py
- ogr/services/github.py
- ogr/services/gitlab.py
- ogr/services/pagure.py
- tests/integration/test_gitlab.py
- Fix the naming issues in GitLab API and add the skeleton of the non-implemented methods.
- Fix API for update_pr_info.
> Fix the inconsistences in the GitLab API

- ogr/services/pagure.py
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Forks.test_create_fork.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Forks.test_fork.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Forks.test_fork_property.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_owners.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.PullRequests.test_pr_create.yaml
- tests/integration/test_pagure.py
- Test creating Pagure PRs and fix some username problems in Pagure tests.
- Creating Pagure PRs calls upstream project url (not the url of fork).
Fixes: #161
> Fix creating Pagure PRs

- ogr/utils.py
fix the issue causing that older ogr does not know what is exception in init.
do not store values what are empty
> fix backward compafibility for tests

- ogr/factory.py
- Fix some typing issues in factory.py.
Reason: typing problems in the packit code on top of it.
> Fix typing in factory

- ogr/services/gitlab.py
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_get_latest_release.yaml
- tests/integration/test_gitlab.py
> method get_latest_release

- ogr/services/gitlab.py
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_description.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_git_urls.yaml
- tests/integration/test_gitlab.py
> gitlab: project info methods

- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_branches.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_email.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_description.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_file.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_git_urls.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_sha_from_tag.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_nonexisting_file.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_username.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_close_issue.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_create_issue.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_all_issue_comments.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_list.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_issue_info.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_get_all_pr_comments.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_get_all_pr_commits.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_info.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_list.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_update_pr_info.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_create_release.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_get_latest_release.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_get_releases.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Tags.test_get_tags.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Tags.test_tag_from_tag_name.yaml
- tests/integration/test_gitlab.py
I accidently deleted the testing repo, so I have regenerated the tests on new repo [https://gitlab.com/packit-service/ogr-tests](url)
> tests on new repo

- ogr/services/github.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.Service.test_project_create.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Service.test_project_create_in_the_group.yaml
- tests/integration/test_github.py
> github method for creating projects added

- ogr/services/gitlab.py
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_commit_comment.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_commit_statuses.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_commit_statuses.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_set_commit_status.yaml
- tests/integration/test_gitlab.py
> methods for commit status and commit comment

- ogr/persistent_storage.py
- ogr/services/gitlab.py
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_issue_labels.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_labels.yaml
- tests/integration/test_gitlab.py
> methods for pr and issue labels

- ogr/services/gitlab.py
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_owners.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_issue_permissions.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_pr_permissions.yaml
- tests/integration/test_gitlab.py
Fixes #169. I used https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions, but I am not sure about the permission for closing of the project issues, I couldn't find more information about that.
> methods for permissions

- ogr/services/github.py
> Factor out getting collaborators (GithubProject)

- ogr/services/github.py
- ogr/services/gitlab.py
- ogr/services/pagure.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_regex.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_regex_reversed.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_reversed.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments_regex.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments_regex_reversed.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments_reversed.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments_regex.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments_regex_reversed.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments_reversed.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
> Implementation of get_issue_comments for projects

- tests/integration/test_gitlab.py
> Update imports in Gitlab tests

- .zuul.yaml
- files/tasks/checkout_packit.yaml
- files/zuul-reverse-dep-packit.yaml
- Add reverse-dependence-test of packit.
> Reverse dependency testing of packit

- ogr/exceptions.py
- ogr/services/pagure/service.py
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create_in_the_group.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create_invalid_namespace.yaml
- tests/integration/test_pagure.py
> Add project_create to PagureService and add tests for it

- .pre-commit-config.yaml
Test for https://github.com/packit-service/packit-service/pull/164
- should pass
> Add rebase check to pre-commit (pass)

- ogr/parsing.py
- ogr/services/github/project.py
- ogr/services/pagure/comments.py
As part of issue #251 improve the typehinting within the repo. This pull request aims to fix the type hints in the parsing.py file.
> improve typehints for parsing.py

- ogr/services/pagure/comments.py
- Update annotation of `_from_raw_comment`
> Comment: mypy

- README.md
- Add link to contribution guide to README.
- Rebased version of #166.
> Link to contribution guide (rebased version of #166)

- ogr/utils.py
Aims to remove any strict MyPy errors from the utils.py file, relating to ticket #251
> improve typehint coverage in utils.py

- ogr/abstract.py
As part of issue #251 update type hinting within the abstract.py file such that there are no mypy errors for that file
> Improve type hint coverage in abstract.py

- files/tasks/packit_reverse_dep_test.yaml
- files/zuul-reverse-dep-packit.yaml
- Fix the path to the packit tests.
> Fix ogr rev dep tests

- ogr/services/github/project.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.PullRequests.test_pr_close.yaml
- tests/integration/test_github.py
Hi,
i have implemented GithubProject.pr_close(). integration test included. Working on unit test.
> implement GithubProject.pr_close()

- ogr/utils.py
This PR contains possible solution of #178 
Closes #178
> Implementation of GitPython instead of calling subprocess

- .packit.yaml
- ci.fmf
- Increase version for packit propose-update.
> Packit config update

- ogr/abstract.py
- ogr/read_only.py
- ogr/services/github/comments.py
- ogr/services/github/issue.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/comments.py
- ogr/services/gitlab/issue.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/comments.py
- ogr/services/pagure/issue.py
- ogr/services/pagure/pull_request.py
- ogr/utils.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_updates.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_pr_comments_updates.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_issue_comments_updates.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_comments_updates.yaml
- tests/integration/test_github.py
- tests/integration/test_github_readonly.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
- tests/unit/test_utils.py
editing comments works only on `body`
> Implement editing comments and backward-link to Issue/PR

- ogr/abstract.py
> Fix typo in comments

- ogr/abstract.py
- ogr/read_only.py
- ogr/services/base.py
- ogr/services/github/flag.py
- ogr/services/github/project.py
- ogr/services/gitlab/flag.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/flag.py
- ogr/services/pagure/project.py
- ogr/services/pagure/pull_request.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_commit_statuses.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_set_commit_status.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.PullRequests.test_pr_status.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_commit_statuses.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_set_commit_status.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_status.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_commit_statuses.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.PagureProjectTokenCommands.test_pr_status.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
Comparison of statuses:
GitHub | GitLab | Pagure
--- | --- | ---
`pending` | `pending` | `pending`
`success` | `success` | `success`
`failure` | `failed` | `failure`
`error` | `-` | `error`
`-` | `canceled` | `canceled`
`-` | `running` | `-`
> Commit flags

- ogr/abstract.py
- ogr/services/github/flag.py
- ogr/services/gitlab/flag.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/flag.py
- Allow creating sommit flags with commit state as a string.
> Fix flags to be compatible with string states

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/flag.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/flag.py
- ogr/services/pagure/project.py
- Add trim commit flag descripttion to all implementations.
> Trim description of commit flag to abstract

- ogr/services/pagure/service.py
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create_unauthorized_namespace.yaml
- tests/integration/test_pagure.py
> Add resolution of failure of Pagure's project_create

- ogr/services/github/project.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_tags.yaml
- tests/integration/test_github.py
> Implement get_tags for GithubProject

- ogr/abstract.py
- ogr/services/github/issue.py
- ogr/services/github/project.py
- ogr/services/gitlab/issue.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/issue.py
- ogr/services/pagure/project.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.Issues.test_issue_list_assignee.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Issues.test_issue_list_author.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.Issues.test_issue_list_nonexisting_author.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_list_assignee.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_list_author.yaml
- tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_list_nonexisting_author.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_list_assignee.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_list_author.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_list_nonexisting_author.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
> Add filtering of issues/PRs by author/assignee

- ogr/services/github/pull_request.py
- tests/integration/test_github.py
> github.pr.author: use login instead of name

- ogr/services/pagure/service.py
improve pagure error response to show additional info stored under 'errors' key
> improve pagure error response

- ogr/abstract.py
- ogr/read_only.py
- ogr/services/base.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/pull_request.py
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
- Add diff_url to the PR classes.
- Add missing setters to abstract PR class.
A rebased version of https://github.com/packit-service/ogr/pull/280 .
> diff url for pull-requests

- ogr/factory.py
- tests/integration/test_data/test_factory/tests.integration.test_factory.FactoryTests.test_get_project_github.yaml
- tests/integration/test_factory.py
Fixes #306
Franto, we didn't speak about this, but this how I expect it to work, WDYT?
> enable getting projects defined with SSH URLs

- Makefile
- files/tasks/rpm-test-deps.yaml
- files/zuul-install-requirements-pip.yaml
- files/zuul-install-requirements-rpms.yaml
- ogr/services/github/issue.py
- ogr/services/gitlab/project.py
- tests/integration/test_data/test_github/tests.integration.test_github.GenericCommands.test_issue_permissions_cant_close.yaml
- tests/integration/test_data/test_github/tests.integration.test_github.Issues.test_issue_list_labels.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
Fixes #353
Also fixes some test failures, let's see...
> invoke tests directly with pytest

- ogr/services/github/project.py
- tests/integration/test_data/test_github_app/tests.integration.test_github_app.GithubTests.test_github_proj_no_app_creds.yaml
- tests/integration/test_github_app.py
~~Blocked on #357~~
Replaces an error like this:
```
github.GithubException.GithubException: 401 {"message":"'Issuer' claim ('iss') must be an Integer","documentation_url":"https://developer.github.com/v3"}
```
> github: raise when we didn't obtain install id

- ogr/services/pagure/service.py
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PagureProjectTokenCommands.test_token_is_none_then_set.yaml
- tests/integration/test_pagure.py
the "errors" may not be set
Fixes #334
> print pagure API errors properly

- ogr/abstract.py
- ogr/services/github/flag.py
- ogr/services/gitlab/flag.py
- ogr/services/pagure/flag.py
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
Add datetime to commit flags #344
> Add datetime to commitflags

- ogr/services/pagure/service.py
added CentOS prod/stg instances to pagure service
> added CentOS prod/stg instances to pagure service

- fedora/python-ogr.spec
my bad, didn't notice packit changed it and I committed it.
> spec: dont hardcode name/version, use macros instead

- ogr/services/pagure/issue.py
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PagureProjectTokenCommands.test_issue_update_description.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PagureProjectTokenCommands.test_issue_update_title.yaml
- tests/integration/test_pagure.py
> Implement Issue setters for Pagure

- ogr/services/pagure/service.py
> Switch backticks to apostrophes in Pagure errors

- ogr/services/github/pull_request.py
- ogr/services/gitlab/pull_request.py
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_head_commit.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_head_commit.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_head_commit.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
Closes #368
-  [x] Implements `head_commit` for Github and Gitlab
-  [x] Integration tests for all implementations
> Head commit on PRs

- ogr/services/pagure/project.py
The best solution though would be to make this list configurable. But I'm in a hurry now :slightly_smiling_face: 
> Declare repositories on git.centos.org not private

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/test_data/test_github/tests.integration.test_github.GenericCommands.test_add_user.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.GenericCommands.test_add_user.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.GenericCommands.test_add_user.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
Fixes #216 
Added to Github and Gitlab, Pagure is still left to do.
> Adding collaborators to projects - (Github, Gitlab, Pagure)

- ogr/factory.py
- tests/unit/test_factory.py
- Update `custom_mapping` with the info provided in the `custom_instances`.
- Fixes: https://github.com/packit-service/ogr/issues/417
> Fix factory.get_project

- ogr/services/github/pull_request.py
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_pr_create_fork_other_fork.yaml
- tests/integration/test_github.py
- tests/unit/test_github.py
Fixes #406
-  [x] Fix unit tests
> Creating PRs from `fork` to `other-fork` on Github

- COMPATIBILITY.md
- README.md
> Add compatibility table

- ogr/services/gitlab/pull_request.py
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_create_pr_fork_fu_ignored.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_create_pr_fork_other_fork.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_create_pr_upstream_fork.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_create_pr_upstream_forkusername.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_create_pr_upstream_upstream.yaml
- tests/integration/test_gitlab.py
> Pull requests on Gitlab

- ogr/__init__.py
- ogr/abstract.py
- ogr/factory.py
- ogr/read_only.py
- ogr/services/base.py
- ogr/services/github/project.py
- ogr/services/github/user.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- ogr/services/pagure/pull_request.py
- ogr/services/pagure/user.py
- ogr/utils.py
- Remove unused util functions.
- Refactor using [sourcery](https://sourcery.ai/).
> Sourcery refactor

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.GenericCommands.test_request_access.yaml
- tests/integration/test_gitlab.py
Request project access - using it here (https://github.com/packit-service/packit-service/pull/740)
[Request access docs](https://python-gitlab.readthedocs.io/en/stable/gl_objects/access_requests.html)
> Requesting project access

- ogr/services/github/issue.py
- tests/integration/test_data/test_github/tests.integration.test_github.Issues.test_issue_without_label.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.Issues.test_create_issue.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.Issues.test_issue_without_label.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
> Create issue in Github without labels

- .pre-commit-config.yaml
- ogr/services/github/auth_providers/github_app.py
- ogr/services/github/comments.py
- ogr/services/github/project.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/service.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
- tests/unit/test_github.py
*  Update pre-commit
*  Fix imports from PyGithub
*  Type-cast `release.created_at` from datetime to string
> Update pre-commit configuration and fix mypy remarks

- ogr/parsing.py
- tests/unit/test_parsing.py
- Support multi-part namespaces in parsing.
> Support multi part namespaces

- ogr/abstract.py
- ogr/factory.py
- ogr/services/base.py
- ogr/services/gitlab/service.py
- tests/unit/test_factory.py
- tests/unit/test_github.py
- tests/unit/test_gitlab.py
- tests/unit/test_pagure.py
- Add hostname property to service class.
- Fix inheritance of `GitlabService` from `BaseGitService`.
- Fixes: #338
> Implement hostname property

- CONTRIBUTING.md
Closes #209 
merge after packit/contributing#1
> Extend contribution guide

- ogr/abstract.py
- ogr/services/github/service.py
- ogr/services/gitlab/service.py
- tests/integration/github/test_data/test_service/tests.integration.github.test_service.Service.test_project_create_with_description.yaml
- tests/integration/github/test_service.py
- tests/integration/gitlab/test_data/test_service/tests.integration.gitlab.test_service.Service.test_project_create_with_description.yaml
- tests/integration/gitlab/test_service.py
- tests/integration/pagure/test_data/test_service/tests.integration.pagure.test_service.Service.test_project_create_with_description.yaml
- tests/integration/pagure/test_service.py
- Add description argument to all `project_create` methods.
> Unify project_create method

- ogr/abstract.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/gitlab/test_data/test_generic_commands/tests.integration.gitlab.test_generic_commands.GenericCommands.test_project_exists.yaml
- tests/integration/gitlab/test_data/test_generic_commands/tests.integration.gitlab.test_generic_commands.GenericCommands.test_project_not_exists.yaml
- tests/integration/gitlab/test_generic_commands.py
> Implement project.exists for GitLab

- ogr/abstract.py
- ogr/services/github/issue.py
- ogr/services/github/project.py
- ogr/services/gitlab/issue.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/issue.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_issues/tests.integration.github.test_issues.Issues.test_create_issue_with_assignee.yaml
- tests/integration/github/test_data/test_issues/tests.integration.github.test_issues.Issues.test_create_private_issue.yaml
- tests/integration/github/test_issues.py
- tests/integration/gitlab/test_data/test_issues/tests.integration.gitlab.test_issues.Issues.test_create_issue_with_assignee.yaml
- tests/integration/gitlab/test_issues.py
- tests/integration/pagure/test_data/test_issues/tests.integration.pagure.test_issues.Issues.test_create_issue_with_assignees.yaml
- tests/integration/pagure/test_issues.py
> Add assignees argument while creating issue

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_generic_commands/tests.integration.github.test_generic_commands.GenericCommands.test_delete.yaml
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/tests.integration.gitlab.test_generic_commands.GenericCommands.test_delete.yaml
- tests/integration/gitlab/test_generic_commands.py
- tests/integration/pagure/test_data/test_generic_commands/tests.integration.pagure.test_generic_commands.GenericCommands.test_delete.yaml
- tests/integration/pagure/test_generic_commands.py
> Adding delete project functionality

- ogr/services/gitlab/service.py
- tests/integration/gitlab/test_data/test_service/tests.integration.gitlab.test_service.Service.test_service_without_auth.yaml
- tests/integration/gitlab/test_service.py
- Allows no-auth read-only access to GitLab
- authenticates only if provided token
Fixes #481
> Fix anonymous GitlabService

- ogr/parsing.py
- ogr/services/pagure/service.py
- tests/unit/test_parsing.py
> Add more tests to parsing and improve parsing

- .packit.yaml
This is partly a dog-fooding of packit.
> Trigger scratch koji build for fedora-devel on PRs

- ogr/abstract.py
- ogr/services/gitlab/flag.py
- Add an abstract class with `__repr__` definition
- Enhances debugging
Fixes #365
*Edit tt: added Fixes line*
> Add an abstract class with binding of repr to str

- ogr/abstract.py
- ogr/services/gitlab/user.py
- Also fix other `__str__`s and reformat them
> Add missing `__str__`s used in tests and format them

- .packit.yaml
Discussed in packit/packit-service#890
> [.packit.yaml] Set copy_upstream_release_description to true

- ogr/services/gitlab/flag.py
> Change exception for edited on GitLab's commit flag

- files/tasks/rpm-test-deps.yaml
> Remove 'master' from task name

- ogr/services/github/project.py
- tests/integration/github/test_data/test_generic_commands/tests.integration.github.test_generic_commands.GenericCommands.test_project_exists.yaml
- tests/integration/github/test_data/test_generic_commands/tests.integration.github.test_generic_commands.GenericCommands.test_project_not_exists.yaml
- tests/integration/github/test_generic_commands.py
Implemented project.exists for GitHub. #480
@lachmanfrantisek  Please review.
> Implemented project.exists for GitHub (#480)

- ogr/abstract.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/pull_request.py
- tests/integration/github/test_data/test_pull_requests/tests.integration.github.test_pull_requests.PullRequests.test_commits_url.yaml
- tests/integration/github/test_pull_requests.py
- tests/integration/gitlab/test_data/test_pull_requests/tests.integration.gitlab.test_pull_requests.PullRequests.test_commits_url.yaml
- tests/integration/gitlab/test_pull_requests.py
- tests/integration/pagure/test_data/test_pull_requests/tests.integration.pagure.test_pull_requests.PullRequests.test_commits_url.yaml
- tests/integration/pagure/test_pull_requests.py
> Implement commits_url for pull requests

- CHANGELOG.md
- fedora/python-ogr.spec
> Release 0.20.0

- ogr/services/pagure/project.py
- tests/integration/pagure/test_data/test_generic_commands/tests.integration.pagure.test_generic_commands.GenericCommands.test_get_files.yaml
- tests/integration/pagure/test_generic_commands.py
> Implement get_files for Pagure

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- tests/integration/github/test_data/test_releases/tests.integration.github.test_releases.Releases.test_latest_release_doesnt_exist.yaml
- tests/integration/github/test_releases.py
- tests/integration/gitlab/test_data/test_releases/tests.integration.gitlab.test_releases.Releases.test_get_latest_release_doesnt_exist.yaml
- tests/integration/gitlab/test_releases.py
In case there is no existing release, instead of failing with an exception
return `None`.
Fixes #540
> Fix getting latest release

- CHANGELOG.md
> Write a changelog entry for release 0.22.0

- README.md
worked on issue: https://github.com/packit/ogr/issues/534
> added packit.github.io/ogr to readme

- files/tasks/packit-requirements.yaml
The file has been renamed since packit/packit@970ec25
> Fix reverse-dep-packit-tests

- .packit.yaml
This is a leftover from the attempt to set up rpmautspec.
> packit.yaml: Remove bogus synced_files config

- .pre-commit-config.yaml
- tests/integration/github/test_service.py
- tests/integration/gitlab/test_generic_commands.py
- tests/integration/pagure/test_generic_commands.py
> Add pyupgrade to pre-commit to match packit's config

- ogr/services/github/pull_request.py
- tests/integration/github/test_data/test_pull_requests/tests.integration.github.test_pull_requests.PullRequests.test_pr_patch.yaml
- tests/integration/github/test_pull_requests.py
Implementated for GithubPullRequest.
It returns bytes in case there's some binary blob in the patch.
It uses requests to get content from patch's URL because I couldn't find in code any function which will get content from a given URL.
> Add GithubPullRequest.patch property

- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
I see `ogr` logs very sparsely, but I think creating a new fork is quite an important operation (at least for me) to at least debug log it.
---
N/A
> Log (debug) creating of a fork

- COMPATIBILITY.md
`Project.get_files`, `Project.create_issue` with labels and `PullRequest.patch` are now fully supported properties/methods and they should be removed from the `compatibility.md` file.
> Update compatibility.md: remove fully supported properties

- CONTRIBUTING.md
Let contributors know about propagate their chandes in our COMPATIBILITY.md file if necessary. 
Maybe we can think about a PR template to remind contributors this as @lachmanfrantisek suggested.
> Let contributors know about changing the COMPATIBILITY.md

- ogr/services/github/check_run.py
I'm about to [remove the app name from the check run names](https://github.com/packit/packit-service/pull/1281) so this will be useful (for example in the validation script).
---
N/A
> Add app property to GithubCheckRun

- .packit.yaml
> Trigger koji build for new dist-git commits

- ogr/abstract.py
- ogr/services/base.py
- ogr/services/gitlab/project.py
- tests/integration/github/test_data/test_pull_requests/PullRequests.test_target_branch_head_commit.yaml
- tests/integration/github/test_pull_requests.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_file.yaml
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_file_content.yaml
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_sha_from_tag.yaml
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_nonexisting_file.yaml
- tests/integration/gitlab/test_data/test_pull_requests/PullRequests.test_target_branch_head_commit.yaml
- tests/integration/gitlab/test_data/test_releases/tests.integration.gitlab.test_releases.Releases.test_create_release.yaml
- tests/integration/gitlab/test_data/test_releases/tests.integration.gitlab.test_releases.Releases.test_get_latest_release.yaml
- tests/integration/gitlab/test_data/test_releases/tests.integration.gitlab.test_releases.Releases.test_get_releases.yaml
- tests/integration/gitlab/test_data/test_releases/tests.integration.gitlab.test_releases.Releases.test_get_releases_pagination.yaml
- tests/integration/gitlab/test_data/test_tags/tests.integration.gitlab.test_tags.Tags.test_tag_from_tag_name.yaml
- tests/integration/gitlab/test_pull_requests.py
- tests/integration/pagure/test_data/test_pull_requests/PullRequests.test_target_branch_head_commit.yaml
- tests/integration/pagure/test_pull_requests.py
• Also add missing parentheses to ‹NotImplementedError›
Related to packit/packit-service#1224
---
_TODO_
> Add head commit of target branch to PullRequest

- .github/PULL_REQUEST_TEMPLATE.md
is this clear?
related: https://github.com/packit/packit/pull/1479
> github PR template: explicit release notes section

- .packit.yaml
> Add srpm_build_deps to the config

- .pre-commit-config.yaml
- CHANGELOG.md
- fedora/python-ogr.spec
> Release 0.36.0

- .packit.yaml
We want to use the staging instance for our own packages.
> Use Packit stage instance for downstream jobs

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_commit_comment.yaml
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_get_commit_comments.yaml
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_commit_comments.yaml
- tests/integration/gitlab/test_generic_commands.py
and implement it in `GithubProject` and `GitlabProject` (`Pagure` doesn't support commit comments)
TODO:
> Add GitProject.get_commit_comments()

- .packit.yaml
> Add allowed_pr_authors for Koji build job in Packit config

- .packit.yaml
> Build stable commits in packit-stable Copr repo

- .github/workflows/do-release.yml
> Strip away # lines

- .github/workflows/do-release.yml
> Fix awk line

- .github/workflows/do-release.yml
> Fix github token name

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_write_access_to_repo.yaml
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_write_access_to_repo.yaml
- tests/integration/gitlab/test_generic_commands.py
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_write_access_to_repo.yaml
- tests/integration/pagure/test_generic_commands.py
Related to [packit-service/#1654](https://github.com/packit/packit-service/pull/1654)
Using the method `users_with_write_access` you can generate the set of users that have write access to the project and the method `has_write_access(user)` you can find out if the user has write access to the project.
> Write access to project

- ogr/services/pagure/project.py
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_no_file_server_error.yaml
- tests/integration/pagure/test_generic_commands.py
Do not try to parse a Pagure server error response when retrieving packit config file.
Fixes packit/packit-service#1629
> Deal with errors while retrieving file from Pagure

- ogr/__init__.py
- ogr/abstract.py
- ogr/services/github/service.py
- tests/unit/test_github.py
Fixes packit/packit-service#1879
Merge before packit/packit-service#1902
> Authentication method can now be customized

- .github/workflows/pypi-publish.yml
This reverts commit 4432979b9bdb49be1cd263ab564df098f26c6505.
> Revert "ci(pypi): use ‹fetch-tags› from ‹actions/checkout›"

- .github/workflows/prepare-release.yml
In specfile this change fixed the issue: https://github.com/packit/specfile/actions/workflows/prepare-release.yml
> Use latest version of the create-pull-request action
