packit/ogr

- python-ogr.spec
```
git checkout 0.0.2
python3 ./setup.py sdist
mv ./dist/ogr-0.0.2.tar.gz .
rpmbuild ./*.spec --define "_sourcedir ${PWD}" --define "_specdir ${PWD}" --define "_builddir ${PWD}" --define "_srcrpmdir ${PWD}" --define "_rpmdir ${PWD}" -bs
fedora-review -n python-ogr -m fedora-29-x86_64
```
Once merged, I'll open a Fedora review for ogr. Franta could do it so he can get the pkgr perms.
> add RPM spec file

- .packit.yaml
With these changes, `packit srpm` should *just work*.
> update packit.yaml to reflect packit==0.2.0

- CHANGELOG.md
Hi,
you have requested a release PR from me. Here it is!
This is the changelog I created:
* Utilize gitchangelog feature of r-bot. [Tomas Tomecek]
* Merge pull request #35 from TomasTomecek/update-packit-yaml. [Tomas Tomecek]
update packit.yaml to reflect packit==0.2.0
* Update packit.yaml to reflect packit==0.2.0. [Tomas Tomecek]
* Merge pull request #34 from jpopelka/no-dimensions. [Jiri Popelka]
pre-commit config & black/Flake8/mypy fixes
* Black & Flake8 & mypy fixes. [Jiri Popelka]
* .pre-commit-config.yaml. [Jiri Popelka]
* Merge pull request #32 from packit-service/releases. [Jiri Popelka]
Releases
* Add test and docs for GitHub releases. [Radoslav Pitonak]
* Add releases for github. [Frantisek Lachman]
* Merge pull request #27 from jpopelka/ci. [Jiri Popelka]
Tox & Jenkinsfile
* …
> 0.1.0 release

- ogr/services/our_pagure.py
- tests/integration/test_pagure.py
https://pagure.io/pagure/issue/4427
```
$ pytest-3 -k test_fork
=== test session starts ===
platform linux -- Python 3.7.3, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
rootdir: /home/tt/g/user-cont/ogr, inifile:
plugins: cov-2.5.1
collected 76 items / 72 deselected
tests/integration/test_github.py s             [ 25%]
tests/integration/test_pagure.py ..            [ 75%]
tests/unit/test_pagure.py .                    [100%]
==== 3 passed, 1 skipped, 72 deselected in 8.83 seconds ===
```
> pagure/get_urls: fill in {username}

- CONTRIBUTING.md
- Makefile
- ogr/mock_core.py
- tests/integration/test_github.py
- tests/integration/test_pagure.py
- Add Makefile targets for removing response files.
- Determine forcewrite mode from file existance.
Why?
- less magic
- easier for newcomers:
- When adding a new test, you need to rerun the tests to generate the response files.
- To update a response file, you need to remove the file and rerun the tests.
TODO:
> Forcewrite mode from file existance

- ogr/utils.py
> unify external command invocation

- ogr/mock_core.py
Fixes
_DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working_
> collections.Hashable -> collections.abc.Hashable

- ogr/abstract.py
- ogr/services/github.py
- ogr/services/pagure.py
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_owners.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_issue_permissions.yaml
- tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_pr_permissions.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_owners.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_issue_permissions.yaml
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_pr_permissions.yaml
- tests/integration/test_github.py
- tests/integration/test_pagure.py
Implementation of getting project owners related to #88. 
And getting users with permission for closing Issues and merging PR based on [Github permissions](https://help.github.com/en/articles/repository-permission-levels-for-an-organization) and [Pagure permissions](https://docs.pagure.org/pagure/usage/project_acls.html) related to issue #100.
> get project's owners and permissions of various users

- ogr/abstract.py
- ogr/services/github.py
- ogr/services/pagure.py
- tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_releases.yaml
- tests/integration/test_pagure.py
Functions `get_release` and `get_releases` implemented in services/github.py were missing in the abstract.py. I also fixed notes from PR #101 which was added after PR was merged. 
**Edit:** I also added functionality `get_releases` for Pagure in the second commit.
> add get_release/get_releases into abstract.py

- ogr/exceptions.py
- ogr/persistent_storage.py
I checked it's not used anywhere else.
> PersistenStorageException -> PersistentStorageException

- ogr/abstract.py
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
By PR #144 we add a bug. In `github.py` is mentioned https://github.com/packit-service/ogr/blob/master/ogr/services/github.py#L398 `get_all_pr_commits`.
Suddenly it was not caught by PR review.
> Rename get_pr_commits to get_all_pr_commits in abstract.py

- ogr/services/pagure.py
Don't use the api url when populating the data for an issue. Use
the web url so that it can be used in a web browser.
Fixes #146
> pagure: use web url in issue

- ogr/services/base.py
- ogr/services/gitlab.py
- ogr/services/pagure.py
- tests/integration/test_data/test_factory_data_tests.integration.test_factory.FactoryTests.test_get_project_gitlab.yaml
- tests/integration/test_factory.py
- tests/integration/test_gitlab.py
- tests/unit/test_factory.py
- Remove repo specific methods from GitlabService.
- Make the creation of gitlab objects lazy.
- Add tests for gitlab service-mapping.
- Make the pagure service mapping more general.
- Add gitlab to service mapping.
> Add gitlab to service mapping

- ogr/services/mock/gitlab.py
- tests/integration/test_gitlab.py
- Not overwrite the gitlab token when set on read-mode.
- Support GitlabAuthenticationError in response files as well.
> Support GitlabAuthenticationError

- ogr/exceptions.py
This pull request intends to fix the strict mypy errors in the exceptions.py file as part of #251. Not sure if the types within the dictionary (str, str) are consistent with how this is used as couldn't see any instances in the codebase where this error is raised with the kwargs filled in.
> Improve typehints for exceptions.py

- tests/integration/test_factory.py
- tests/integration/test_github.py
- tests/integration/test_github_app.py
- tests/integration/test_github_readonly.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
Closes #281 
After change in requre integration tests fails. 
Change PersistentObjectStorage().is_write_mode to PersistentObjectStorage().mode == StorageMode.write
Zuul allow to add relation between repos, maybe this is a option to prevent that situation, but I don't know how looks policy about that in packit-service.
> Fix integration tests

- ogr/parsing.py
- tests/unit/test_parsing.py
Hello there 👋 
This came up in my `good-first-issue` search and seemed like a fairly straightforward bug to fix.
I decided to treat it as a data problem and check for the existence of a trailing slash in a simple if statement. It worked in the test cases I passed it, and should be pretty straightforward to debug. 
Open to any/all criticism. Thanks for all you do!
> Remove trailing slash from URLs before parsing

- .gitignore
While working on #319, I noticed that there was no `.gitignore` file in the repository.
To solve my _own_ pain points while developing, I generated this one, which should ignore standard files for MacOS, Windows, & Linux, and additionally ignore files that are generally good to ignore in Python projects.
> Add `.gitignore` to repo

- ogr/services/pagure/issue.py
- ogr/services/pagure/project.py
This commit allows to pass a list of tags to pagure's create_issue method.
Signed-off-by: Clement Verna <cverna@tutanota.com>
> Add support for tags when creating pagure issues.

- ogr/services/github/service.py
- ogr/services/gitlab/service.py
- ogr/services/pagure/service.py
- Do not use tokens/private_keys in the `__str__` methods.
- used `set`/`not set` instead
- reason: We've started to show logs publicly in the packit-service and it can be easy to forget about this "feature".
> Do not use tokens and keys in the __str__ methods

- ogr/abstract.py
- ogr/services/github/flag.py
- tests/integration/test_github.py
- Set missing info in GitHub commit flags.
- Test was improved to cover that.
> Fix GitHub commit flags

- .packit.yaml
we are setting this so we can use packit from ogr's dist-git
packit can't know what's the upstream name when running from distgit
> packit.xml: set upstream_package_name

- ogr/services/pagure/pull_request.py
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_set_pr_flag.yaml
- tests/integration/test_pagure.py
Flags on PRs are specific to Pagure.
Other forges allow setting flags/statuses only on commits and will
display the flags for the PR head on the PR page, if any is set.
Due to the above this method is added only to PagurePullRequests, and we
expect OGR library users to implement the "show the flags of the last
commit for the PR" behaviour for Pagure, in case they need it.
> Set PR flags in Pagure

- ogr/services/gitlab/flag.py
- ogr/services/gitlab/project.py
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.GenericCommands.test_branches_pagination.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.Releases.test_get_releases_pagination.yaml
- tests/integration/test_gitlab.py
Supposed to Fix #391 
As far as I understand the `python-gitlab` package, they follow Gitlab's REST API with few additions like `list()` methods on some objects.
-  [x]  (#391) Branches API does neither state returning paginated list or explicitly say it returns *all* branches
works with `all=True` even though it's not documented in Gitlab API
-  [x]  will have to try using it at some repository with many branches (default pagination is 20 in other API endpoints) or could you provide the repository that brought this issue to light? ;)
-  [x]  Repository tree - can't find `all` parameter in API, it is used though and there is pagination => should look into that
same, works even though it's not in the API documentation
-  [x]  Releases list - by API it is paginated, there's no mention of …
> GitLab pagination

- fedora/python-ogr.spec
packaging guidelines say this is automatic since F33 and we should
disable it
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_provides
> spec: don't do python_provide on F33+

- ogr/abstract.py
- ogr/services/base.py
- ogr/services/github/project.py
- ogr/services/github/pull_request.py
- ogr/services/github/service.py
- ogr/services/gitlab/pull_request.py
- ogr/services/gitlab/service.py
- ogr/services/pagure/pull_request.py
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_fork_fork.yaml
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_other_fork_fork.yaml
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_renamed_fork.yaml
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_renamed_upstream.yaml
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_upstream_branch.yaml
- tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_upstream_fork.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_fork_fork.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_other_fork_fork.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_renamed_fork.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_renamed_upstream.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_upstream_branch.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_upstream_fork.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_source_project_upstream_branch.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_source_project_upstream_fork.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
Closes #400
(copied from issue)
-  [x] squash commits
-  [x] check getting projects by internal representation (github: creating from github.Repository, gitlab: from project_id)
-  [x] Github: project uses almost the same way of initializing `GithubProject` in `L129, L172, L385, L564`
-  [x] deprecating `.project`
-  [x] provide `.project` as a property?
-  [ ] if so, do we need setters for them outside class?
-  [ ] consider having `GithubProject.from_github_repository`, which would take just the github repo from PyGithub and return new project
-  [ ] consider creating GitLab projects just from _project id_ (python-gitlab doesn't offer any way to get to source project than ID)
> Enhance project references in pull requests

- ogr/services/github/pull_request.py
- tests/unit/test_github.py
Related to #307 
If the fork_name arg is passed, PR is created on the forked repo.
If the fork_name arg is not passed PR is made to parent repo. 
Tested for (fork-fork, fork-upstream, upstream-upstream)
> Create PR's to forked Repo fixed for Github

- ogr/services/github/project.py
- tests/integration/test_data/test_github/tests.integration.test_github.GenericCommands.test_pr_permissions.yaml
- tests/integration/test_github.py
When telling if a user can merge PRs in a GitHub repo, ask GitHub for
the user's permission on the repo instead of checking if the user is in
the list of collaborators.
This should lead to fewer API calls in cases when the full list of
collaborators is not needed, but it also returns better results: the
list of collaborators does not seem to be always up to date when queries
are done using GitHub App tokens.
Relates to packit-service/packit-service#612.
> GitHub: query only one user when telling if a user can merge PRs

- ogr/abstract.py
- ogr/services/pagure/pull_request.py
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_pr_patch.yaml
- tests/integration/test_pagure.py
Currently implemented only for PagurePullRequest.
It returns bytes in case there's some binary blob in the patch.
I'd like to use this in https://github.com/packit-service/packit-service/pull/627
> Add PullRequest.patch property

- .packit.yaml
- README.md
- Build in Copr for master commits and releases.
- We are using same copr projects as we do for packit.
- Relates to https://github.com/packit-service/ogr/pull/428.
> Copr build for master and releases

- ogr/services/gitlab/project.py
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.GenericCommands.test_get_file_content.yaml
- tests/integration/test_gitlab.py
The object [gitlab.v4.objects.ProjectFile](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.ProjectFile) with the function [decode()](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.ProjectFile.decode) will return bytes -
`b'---\nspecfile_path: hello.spec\nsynced_files:\n  - hello.spec\n# actions:\n#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."\n# current_version_command: ["python3", "setup.py", "--version"]\n# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]\njobs:\n- job: copr_build\n  trigger: pull_request\n  metadata:\n    targets:\n    - fedora-30-x86_64'`
Expected string - 
```
---
specfile_path: hello.spec
synced_files:
- hello.spec
jobs:
- job: copr_build
trigger: …
```
> Fix get_file_content() returning bytes

- fedora/python-ogr.spec
This is needed for Python 3.10+.
See devel-list message for details:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PQIGCQCRNBYNXBX2ICWEM3PLDLNOG2ZT/
> Replace Python version glob with macro

- .packit.yaml
in https://github.com/packit-service/packit/pull/797
> Job metadata key 'dist_git_branch' was renamed to 'dist_git_branches'

- .pre-commit-config.yaml
- setup.cfg
This reverts commit 74d84893f16f5020e60d2a1ba35e13d768b514f0.
In Centos 8 Python 3.6 is the default python3. Having Python 3.6 support
will make life easier there.
> Revert "Drop python 3.6"

- ogr/abstract.py
- ogr/services/github/issue.py
- ogr/services/github/project.py
- ogr/services/gitlab/issue.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/issue.py
- ogr/services/pagure/project.py
- tests/integration/test_data/test_github/tests.integration.test_github.Issues.test_create_issue.yaml
- tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.Issues.test_create_private_issue.yaml
- tests/integration/test_data/test_pagure/tests.integration.test_pagure.Issues.test_create_issue.yaml
- tests/integration/test_github.py
- tests/integration/test_gitlab.py
- tests/integration/test_pagure.py
> Add support to create private issues.

- ogr/abstract.py
- ogr/services/base.py
- Use parenthesis for `lru_cache` decorator for backwards compatibility.
- Fixes problem found in packit PR: https://github.com/packit/packit-service/pull/820
> Fix lru_cache decorator

- ogr/services/pagure/user.py
Chosen as a better resolution to unsupported API (previously raised an exception).
Closes #126
> Return `None` for user's email in Pagure

- .pre-commit-config.yaml
- Makefile
Turn off requre clean up in pre-commit CI since it times out.
not sure how much it changes running locally, I run manually and had to use `pre-commit run --hook-stage manual --all`
There are no remotes in pre-commit CI?
> Turn off requre in pre-commit CI

- ogr/services/pagure/service.py
This way users of a PagureService object can control how failures of API
calls are retried.
> PagureService: Make retries parametrizable

- Makefile
- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/pagure/test_data/test_generic_commands/tests.integration.pagure.test_generic_commands.GenericCommands.test_get_file.yaml
All git forges support changing of a default branch of a repo/project.
All newly created Github projects have had 'main' as a default branch instead of 'master' since Oct 2020.
- https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch
- https://docs.gitlab.com/ee/user/project/repository/branches/#default-branch
- https://pagure.io/api/0/#projects-tab (List git branches)
>  Add and implement GitProject.default_branch property

- .packit.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1905223
Requires all the dependencies to be in epel-8 as well.
> Enable build and test for epel-8

- .github/workflows/docs.yml
oh, there's the tea https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3
> Add autogeneration of docs

- ci.fmf
This was amended in cf86074e to be compatible with both old/new TF, but can be removed completely now since the old TF no longer exists.
> [ci.fmf] remove old TF specific code

- ogr/services/github/auth_providers/token.py
- ogr/services/github/service.py
- tests/integration/github/test_retries.py
- tests/unit/test_factory.py
This update implements retry mechanism for Github requests.
Number of retry attempts can be set in `GithubService()` and  instances dictionary (used by `get_instances_from_dict()`), eg:
```
{                                                                   
"github.com": {                                                 
"token": "abcd",                                            
"max_retries": "3", 
}                                   
}   
``` 
This allows to enable request retries in packit/packit-service by adding  key `max_retries` to configuration (`authentication -> github -> max_retries`). I'm not sure If this is an acceptable solution, as far as it may be a bit confusing to set number of request retries not necessarily related to authentication in authentication section of …
> Implement retry mechanism for Github

- CONTRIBUTING.md
- Makefile
- ogr/factory.py
- recipe.yaml
- tests/unit/test_factory.py
The current behaviour of 'ogr.get_project()', when a list of
'custom_instances' (already created GitService objects) is provided, is
to raise an OgrException if none of these matches the project URL.
Introduce a 'force_custom_instance' flag, defaulting to True to keep
backwards compatibility, in order to support the use case where the user
would like to retrieve an existing service *or create a new one* if none
is matching in the 'custom_instances' list.
> Allow ignoring custom instances when creating a project

- .packit.yaml
Hunor is correct, our upstream release description used as a %changelog
violates Fedora guidelines, so let packit assemble %changelog from
git-log.
https://docs.fedoraproject.org/en-US/packaging-guidelines/#changelogs
https://packit.dev/docs/configuration/#copy_upstream_release_description
> packit: create downstream %changelog from git-log

- ogr/services/pagure/project.py
- ogr/services/pagure/pull_request.py
- tests/integration/pagure/test_data/test_pull_requests/tests.integration.pagure.test_pull_requests.PullRequests.test_pr_create_from_fork.yaml
- tests/integration/pagure/test_data/test_pull_requests/tests.integration.pagure.test_pull_requests.PullRequests.test_pr_create_from_parent.yaml
- tests/integration/pagure/test_pull_requests.py
PagureProject.create_pr dumped fork_username which made PR creation from
a fork by passing this kwarg not working - one had to create the PR from
an actual fork instance instead of making it the parent repo.
This commit:
* makes sure the fork_username is passed to PagurePullRequest.create
* and also sets correct `repo_from[*]` keys for the API request to
create a PR
Worked for: https://src.fedoraproject.org/rpms/packit/pull-request/125
And also this PR -_-
Fixes #551
~~Please let me know what tests I should write.~~
> pagure: enable creating PRs from fork via fork_username

- setup.cfg
This is the fix for [issue #559](https://github.com/packit/ogr/issues/559)
The file py.typed need to be added at the root of the ogr package for
the package to be PEP-561 compliant and have mypy be able to use the
type information when importing the package in other projects.
> Export types in the package (PEP-561)

- ogr/exceptions.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
Catch `GithubException` in GithubProject.get_file_content as we do
for GitLab and Pagure to:
a) unify the behaviour
b) ignore unwanted 404 related to:
https://sentry.io/organizations/red-hat-0p/issues/1809076278
> Unify behaviour for get_file_content for GitHub

- ogr/services/github/service.py
- ogr/services/gitlab/service.py
- ogr/services/pagure/service.py
I'm tired of
Ignored keyword arguments: {}
and since this change was requested by me, finally decided to improve
the behavior:
1. log only when some kwargs are set
2. set log to debug
> ignored kwargs: set log to debug and only log if set

- CONTRIBUTING.md
- Makefile
Makefile:
Abolish the 'prepare-check' target, merging its functionality into
'check' target.  In 'check' target, conditionally install
- python3-flexmock
- python3-requre
depending on presence/absence of /usr/share/doc/python3-flexmock
and /usr/bin/requre-patch respectively.
Check for
- ansible-bender
- podman
in 'build' target.
Remove all mention of unused python3-tox.
CONTRIBUTING.md:
Remove all mention of unused tox.
Remove mention of prepare-check (merged into 'check' target).
Document installation of python3-flexmock and python3-requre
by 'make check', ansible-bender and podman by 'make build'.
Include note about 7.1 GB of disk space consumed by 'make build'.
Mention conditional installation of
- ansible-bender
- podman
- python3-requre
- python3-flexmock
Minor language & spelling …
> Make 'make check' more consistent, and better documented, across projects

- CONTRIBUTING.md
- Makefile
- README.md
We have decided to remove the prepare-check and prepare-build
targets entirely, relying instead on strongly-worded recommendations
in CONTRIBUTING.md and README.md.
Fixes ogr issue #579.
Signed-off-by: Ben Crocker <bcrocker@redhat.com>
> Make 'make check' more consistent across projects

- ogr/abstract.py
- ogr/services/github/issue.py
- ogr/services/gitlab/issue.py
- ogr/services/pagure/issue.py
- tests/integration/github/test_data/test_issues/Issues.test_issue_assignees.yaml
- tests/integration/github/test_issues.py
- tests/integration/gitlab/test_data/test_issues/Issues.test_issue_assignees.yaml
- tests/integration/gitlab/test_issues.py
- tests/integration/pagure/test_data/test_issues/Issues.test_issue_assignees.yaml
- tests/integration/pagure/test_issues.py
Closes: https://github.com/packit/ogr/issues/586
> add function for adding assignees to issues

- files/zuul-install-requirements-rpms.yaml
- files/zuul-reverse-dep-packit.yaml
- files/zuul-tests.yaml
Previously it was a var, redefined in the base job, but this no longer works (?)
packit/packit-service-zuul#46
> Set project_dir as a fact

- files/tasks/project-dir.yaml
- files/zuul-install-requirements-rpms.yaml
- files/zuul-reverse-dep-packit.yaml
- files/zuul-tests.yaml
- recipe.yaml
This is supposed to fix `requre-reverse-dep-ogr-tests` in requre where we run the ogr tests via ansible-playbook which, I think, creates new environment, where `zuul` variable is not defined.
https://softwarefactory-project.io/zuul/t/packit-service/build/baa15a374a384e759a74a9cf655e80e8
> Set project_dir when zuul is not defined

- Makefile
- ogr/abstract.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/pull_request.py
- tests/integration/github/test_data/test_pull_requests/PullRequests.test_merge_commit_sha.yaml
- tests/integration/github/test_pull_requests.py
- tests/integration/gitlab/test_data/test_pull_requests/PullRequests.test_merge_commit_sha.yaml
- tests/integration/gitlab/test_pull_requests.py
Add merge_commit_sha and mergeable properties to GithubPullRequest class
(and PullRequest superclass).
OGR issue #584.
Signed-off-by: Ben Crocker <bcrocker@redhat.com>
> Support using the merge ref instead of the head ref in a pull request

- plans/linters.fmf
related: https://github.com/packit/packit.dev/issues/259
rpmlint is being executed in Fedora anyway so running it sooner in
upstream will prevent "breakages" during releases
> TF: check specfile with rpmlint

- ogr/services/gitlab/pull_request.py
- tests/integration/gitlab/test_data/test_pull_requests/tests.integration.gitlab.test_pull_requests.PullRequests.test_pr_patch.yaml
- tests/integration/gitlab/test_pull_requests.py
Implementated for GitlabPullRequest.
It returns bytes in case there's some binary blob in the patch.
It uses requests to get content from patch's URL.
Implementation for #416
> Add GitlabPullRequest.patch property

- ogr/services/pagure/service.py
When I `fedpkg[-stage] clone a-package` its remote is `pkgs.[stg.]fedoraproject.org`.
> Add pkgs.[stg.]fedoraproject.org to the list of hosts PagureService is used for

- ogr/services/gitlab/pull_request.py
- tests/integration/gitlab/test_data/test_pull_requests/PullRequests.test_merge_commit_sha.yaml
- tests/integration/gitlab/test_data/test_pull_requests/PullRequests.test_test_merge_commit_sha.yaml
- tests/integration/gitlab/test_pull_requests.py
Previous solution utilized only merge_commit, that is after merging MR.
Since v0.20.0 python-gitlab supports test merges as GitHub. Fixes
behaviour to be consistent with GitHub's.
---
_TODO_
> Fix merge_commit_sha for GitLab

- Makefile
`TEST_TARGET=tests/integration/gitlab/test_forks.py make check-in-container` didn't work for me without it.
> Makefile: pass TEST_TARGET into check-in-container

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/github/comments.py
- ogr/services/gitlab/comments.py
- ogr/services/pagure/comments.py
- tests/integration/github/test_comments.py
- tests/integration/github/test_data/test_comments/Comments.test_get_reactions.yaml
- tests/integration/github/test_data/test_comments/Comments.test_issue_react_to_comment_and_delete.yaml
- tests/integration/github/test_data/test_comments/Comments.test_pr_react_to_comment_and_delete.yaml
- tests/integration/gitlab/test_comments.py
- tests/integration/gitlab/test_data/test_comments/Comments.test_get_reactions.yaml
- tests/integration/gitlab/test_data/test_comments/Comments.test_issue_react_to_comment_and_delete.yaml
- tests/integration/gitlab/test_data/test_comments/Comments.test_pr_react_to_comment_and_delete.yaml
Support for reacting to comments, getting list of reactions and deleting reactions.
Also compatibility.md file - updated. 
Fixes #630 
---
Ogr now supports reacting to the comment with a given reaction, getting them in list and deleting them (only when reaction is added by using ogr API).
> Add Comment.react_to_the_comment, Comment.get_reactions, Reaction.delete

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/github/issue.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/issue.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/issue.py
- tests/integration/github/test_data/test_issues/Issues.test_get_comment.yaml
- tests/integration/github/test_data/test_pull_requests/PullRequests.test_get_comment.yaml
- tests/integration/github/test_issues.py
- tests/integration/github/test_pull_requests.py
- tests/integration/gitlab/test_data/test_issues/Issues.test_get_comment.yaml
- tests/integration/gitlab/test_data/test_pull_requests/PullRequests.test_get_comment.yaml
- tests/integration/gitlab/test_issues.py
- tests/integration/gitlab/test_pull_requests.py
- tests/integration/pagure/test_data/test_issues/Issues.test_get_comment.yaml
- tests/integration/pagure/test_issues.py
I implemented this feature because my PR [packit-service/1222](https://github.com/packit/packit-service/pull/1222) needs to get a comment by its ID but OGR doesn't support that.
This `get_comment` method just simply returns a comment which is identified by comment's ID. Works for PullRequest (not Pagure) and Issue as well.
---
Added support for getting issue and pull request comments by their ID. Pagure currently does not support getting pull request comments.
> Get PR and Issue comment by its ID

- .packit.yaml
- README.md
This is to get rid of the 'packit-master' name.
Also fix the configuration to build 'ogr' in Copr, whenever there is a
new commit on the _main_ branch (not on _master_).
> Build the development version in packit-dev

- tests/integration/github/test_retries.py
Support for plain 'import flexmock' was removed in [flexmock 0.11.0].
Get ready for this.
[flexmock 0.11.0]: https://flexmock.readthedocs.io/en/latest/changelog/#release-0110
> Fix flexmock imports

- ogr/abstract.py
- ogr/read_only.py
- ogr/services/base.py
- ogr/services/github/flag.py
- ogr/services/gitlab/flag.py
- ogr/services/pagure/flag.py
- ogr/services/pagure/pull_request.py
Cleanup of methods and properties which have been marked as deprecated for a long time
Related to https://github.com/packit/packit-service/pull/1262
Merge before/after
---
Methods which have been marked as deprecated and should have already been removed in version 0.14.0 are now removed.
> Remove old deprecated methods

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/github/comments.py
- ogr/services/gitlab/comments.py
- ogr/services/pagure/comments.py
- ogr/services/pagure/pull_request.py
- tests/integration/pagure/test_data/test_pull_requests/PullRequests.test_get_comment.yaml
- tests/integration/pagure/test_pull_requests.py
I want to implement this even Pagure API doesn't support it because this will solve annoying thing in packit-service for me - we have `comment_object` for github and gitlab and pagure but not for pagure PR :see_no_evil: 
Related to #640 
(i am uncertain if the release note below is useful for users but I'll write it down anyway just to be sure)
---
OGR now fully supports getting PR comments by its id.
> Add PagurePullRequest.get_comment by its id

- ogr/services/gitlab/service.py
- tests/integration/gitlab/test_data/test_service/Service.test_list_projects_get_forks.yaml
- tests/integration/gitlab/test_service.py
Problem was that by specifying `gitlab_repo=project` we passed in `GroupProject` which is very limited and doesn't provide all the features of `Project` object. See also Note in [python-gitlab's docs](https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html).
Previously:
```python
gls = GitlabService(token=token, instance_url="https://gitlab.com")
prs = gls.list_projects(namespace="packit-service/src")
print(prs[0].get_forks())
```
Resulted in:
```python
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/gitlab/base.py", line 77, in __getattr__
return self.__dict__["_updated_attrs"][name]
KeyError: 'forks'
```
Now it results in:
```python
[<GitlabProject(namespace="jpopelka", repo="luksmeta")>]
```
---
`GitlabService.list_projects()` was fixed to …
> Correctly convert projects in GitlabService.list_projects()

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_get_sha_from_branch.yaml
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_get_sha_from_branch_non_existing.yaml
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_sha_from_branch.yaml
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_sha_from_branch_non_existing.yaml
- tests/integration/gitlab/test_generic_commands.py
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_get_sha_from_branch.yaml
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_get_sha_from_branch_non_existing.yaml
- tests/integration/pagure/test_generic_commands.py
Required for passing commit hashes from service to testing farm for
merging of tests that are run on their side or usage in tmt preparation.
TODO:
---
We have introduced a new function into `ogr` that allows you to get commit SHA of the HEAD of the branch.
> Implement getter of SHA for branches

- ogr/services/pagure/service.py
- setup.cfg
So that this is also correctly displayed on PyPI.
---
n/a
> Update classifiers to mark support for Python 3.9 and 3.10

- ogr/factory.py
- tests/unit/test_factory.py
Instead of trying to find substring that could indicate usage of specific
git forge, parse the URL first and then look for the indication in parsed
«hostname». That way we avoid situations when parts of service names, e.g.
gitlab or pagure, could be included in the URL and matched with the service
even though they are not part of the hostname.
Fixes #663
TODO:
Factory method for acquiring project or service class from URL has been improved by checking just the hostname for determining the service.
> Improve parsing of service class from URL

- ogr/abstract.py
- ogr/services/base.py
- ogr/services/github/project.py
- ogr/services/github/release.py
- ogr/services/gitlab/project.py
- ogr/services/gitlab/release.py
- ogr/services/pagure/project.py
- ogr/services/pagure/release.py
- tests/integration/gitlab/test_releases.py
- tests/integration/pagure/test_data/test_project_token/PagureProjectTokenCommands.test_create_release.yaml
- tests/integration/pagure/test_project_token.py
breaking changes:
- reordered and renamed parameters for `.create_release`
* also introduced into `GitProject`s API
Fixes #86
Fixes #112
---
Release class in ogr has been reworked and `create_release` has been made part of the API for `GitProject`.
> Releases rework

- ogr/abstract.py
- ogr/read_only.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_forks/Forks.test_create_fork_with_namespace.yaml
- tests/integration/github/test_forks.py
- tests/integration/gitlab/test_data/test_forks/Forks.test_create_fork_with_namespace.yaml
- tests/integration/gitlab/test_forks.py
- tests/integration/pagure/test_data/test_forks/Forks.test_create_fork_with_namespace.yaml
- tests/integration/pagure/test_forks.py
Allow users to fork repositories to specific namespace or organization
rather than their user namespace.
TODO:
Fixes #631
We have added a new optional parameter `namespace` to `fork_create` method on git projects, which allows you to fork project into a specific namespace. (Forking to namespaces is not allowed on Pagure.)
> feat(forks): allow forking to specific namespace

- ogr/abstract.py
- ogr/exceptions.py
- ogr/services/pagure/issue.py
- ogr/services/pagure/project.py
- ogr/services/pagure/pull_request.py
- ogr/services/pagure/service.py
- tests/integration/github/test_forks.py
- tests/integration/github/test_generic_commands.py
Fixes #658
We have introduced a new exception class `GitForgeInternalError` that indicates failure that happened within the forge (indicated via 50x status code). `*APIException` have been given a new superclass `APIException` that provides status code from forge (in case of error, invalid operation, etc.).
> „Exceptional improvements“

- .packit.yaml
- .pre-commit-config.yaml
And use a production instance for downstream jobs until the stage one does not work.
N/A
> Use both prod and stg Packit instance

- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_get_contributors.yaml
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_contributors.yaml
- tests/integration/gitlab/test_generic_commands.py
Implement methods for acquiring contributors to the GitProject.
We have implemented `get_contributors` function in ogr that can be used for getting contributors to the project on GitHub (set of logins) and GitLab (set of authors).
> feat: implement getting contributors

- .packit.yaml
Rawhide updates are created automatically,
but not for not-released branched versions.
We can use `fedora-latest` alias which is the latest non-rawhide branch.
It is not an issue if `fedora-latest` is covered also by `fedora-stable`,
Packit converts all the values to a set
so we don't need to worry about duplicates.
N/A
> Create Bodhi updates for branched development version as well

- ogr/services/github/issue.py
- ogr/services/gitlab/issue.py
- ogr/services/pagure/issue.py
- tests/integration/github/test_issues.py
- tests/integration/pagure/test_data/test_issues/Issues.test_get_comment.yaml
- tests/integration/pagure/test_data/test_issues/Issues.test_issue_assignees.yaml
- tests/integration/pagure/test_data/test_issues/tests.integration.pagure.test_issues.Issues.test_issue_list.yaml
- tests/integration/pagure/test_data/test_issues/tests.integration.pagure.test_issues.Issues.test_issue_list_assignee.yaml
- tests/integration/pagure/test_data/test_issues/tests.integration.pagure.test_issues.Issues.test_issue_list_author.yaml
- tests/integration/pagure/test_data/test_issues/tests.integration.pagure.test_issues.Issues.test_issue_list_labels.yaml
- tests/integration/pagure/test_data/test_issues/tests.integration.pagure.test_issues.Issues.test_issue_list_nonexisting_author.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_comments.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_comments_author.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_comments_author_regex.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_comments_regex.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_comments_regex_reversed.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_comments_reversed.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_info.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_permissions.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_update_description.yaml
- tests/integration/pagure/test_data/test_project_token/tests.integration.pagure.test_project_token.PagureProjectTokenCommands.test_issue_update_title.yaml
Raise ‹IssueTrackerDisabled› in all functions that directly touch the
issues of the project, not just the ‹.create› function.
Reproduced in packit/packit-service#1463
Fixes #702
We have fixed a bug in ogr that caused `IssueTrackerDisabled` being raised only when trying to create an issue on git project with disabled issue tracker. Now it is also raised when getting a specific issue or an issue list.
> fix(issues): raise exception when issues are disabled

- ogr/services/pagure/service.py
When using `PagureService.get_project_from_url` test for correctly parsed
URL before accessing its attributes (resulting in `AttributeError`).
Fixes #698
`ogr` now correctly raises `OgrException` when given invalid URL to `PagureService.get_project_from_url`.
> fix(pagure): raise for invalid URL in pagure

- ogr/exceptions.py
- ogr/services/github/auth_providers/tokman.py
When querying tokman, we can get 400 for suspended or uninstalled GitHub
Apps, in such case raise an appropriate exception that can be handled
later on in a better way.
Fixes #666
Merge before packit/packit#1566
When using Tokman as GitHub authentication mechanism, ogr will now raise `GithubAppNotInstalledError` instead of failing with generic `GithubAPIException` when app providing tokens is not installed on the repository.
> fix(github): raise specific exception from tokman

- setup.cfg
We use `pkg_resources` in `ogr/__init__.py` so it needs to be installed
with the package.
Context: https://bodhi.fedoraproject.org/updates/FEDORA-2022-20fd24ab3c
The packaging issue with missing `pkg_resources` is fixed by requiring `setuptools` as `install_requires` dependency.
> Add setuptools to requirements

- ogr/__init__.py
- setup.cfg
The `setuptools` package is a huge overkill to get self-version.
Use the standard library instead on Python 3.8+,
or a smaller package on older Pythons.
Credits go to Miro Hrončok:
https://github.com/packit/specfile/commit/7ab965a161c14b841c200d3779d7163edd314372
Replaces: #709
Use the standard library instead of `setuptools` for getting the version on Python 3.8+,
or a smaller package on older Pythons.
> Drop runtime dependency on setuptools

- CHANGELOG.md
- fedora/python-ogr.spec
GitHub release content:
```
- When using Tokman as GitHub authentication mechanism, ogr will now raise GithubAppNotInstalledError instead of failing with generic GithubAPIException when app providing tokens is not installed on the repository.
- Use the standard library instead of setuptools for getting the version on Python 3.8+,
or a smaller package on older Pythons.
This also fixes the packaging issue with missing `pkg_resources`.
```
> Prepare release 0.38.1

- ogr/services/github/pull_request.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/pull_request.py
- tests/integration/github/test_pull_requests.py
- tests/integration/gitlab/test_pull_requests.py
- tests/integration/pagure/test_pull_requests.py
The PullRequest target project should be the parent of the forked project when merging from fork.
Fixes packit/hardly#63
> When merging from fork the target is the fork's parent

- .packit.yaml
The key is deprecated and can be removed.
> Remove the 'metadata' key from .packit.yaml

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/pagure/pull_request.py
- tests/integration/pagure/test_pull_requests.py
We have implemented the `closed_by` property for the Pagure pull request for getting the login of the account that closed the pull request.
> Implement closed by property for Pagure PR

- tests/integration/gitlab/test_data/test_issues/Issues.test_issue_list_labels.yaml
Add missing GitLab response after ‹python-gitlab› release.
Fixes #726
> fix(tests): add missing GitLab response

- .github/workflows/do-release.yml
when a new release PR is merged
release PR needs to be labeled with "release" label
> New GitHub workflow: create a release

- Makefile
- files/tasks/generic-dnf-requirements.yaml
- plans/full.fmf
Starting with pytest 7, the shebang in `/usr/bin/pytest` passes the `-s` option to Python interpreter, which prevents importing pip-installed packages and breaks the tests. Fix that.
> Explicitly specify Python interpreter options when running pytest

- ogr/abstract.py
- ogr/exceptions.py
- ogr/read_only.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_generic_commands.py
Related to https://github.com/packit/packit-service/pull/1716
CommitComment.comment has been deprecated in favour of CommitComment.body to make the naming consistent across objects.
> Deprecate CommitComment.comment in favour of body

- ogr/services/github/service.py
Since ‹method_whitelist› is being deprecated.
**Merge once it doesn't break F34**
---
_N/A_
> Switch ‹Retry› constructor to ‹allowed_methods›

- .github/workflows/do-release.yml
- .github/workflows/docs.yml
- .github/workflows/prepare-release.yml
- .github/workflows/pypi-publish.yml
- files/tasks/project-dir.yaml
- files/zuul-install-requirements-pip.yaml
- files/zuul-install-requirements-rpms.yaml
- files/zuul-reverse-dep-packit.yaml
- files/zuul-tests.yaml
- recipe.yaml
Both, the [packit/prepare-release](https://github.com/peter-evans/create-pull-request#action-inputs) & [peter-evans/create-pull-request](https://github.com/packit/prepare-release#packitprepare-release) default to using (autogenerated) [secrets.GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) if no token is provided.
That token should be enough because the steps are repo-scoped and [don't trigger any other workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) since the PR which triggers the 'Create GitHub release' is manually merged by a user.
Seems to work OK - jpopelka/packit#1
> Use github-actions bot to run prepare-release steps

- ogr/services/pagure/service.py
- tests/integration/pagure/test_generic_commands.py
After Maja's changes in c8ddf05, we were raising a ‹PagureAPIException›
also for 50x when getting files from Pagure, e.g. configs in service.
Aforementioned change is rather generic and handles 404s ideally, but not
so ideally 50x that should be retried, as they are the git forge internal
errors, rather than raised up in Sentry after their first occurence.
Let's check for ‹status code >= 500› and raise ‹GitForgeInternalError›
instead of the ‹PagureAPIException›.
TODO:
ogr now raises `GitForgeInternalError` rather than `PagureAPIException` when getting 50x response from the Pagure API.
> fix(pagure): raise network error for 50x

- ogr/services/pagure/pull_request.py
- tests/integration/pagure/test_data/test_pull_requests/PullRequests.test_pr_list.yaml
A bug in ogr resulting in returning only first page of pull requests for Pagure has been fixed.
> fix: get all PRs in PagurePullRequest.get_list instead of one page

- .packit.yaml
- setup.cfg
When we run the following as a sandcastle command:
`python3 setup.py --version`
we got 2 warning messages that make packit fail in **parsing the command output**:
1. `licence_file` is deprecated, which should be resolved by the first commit
2. `Requirements should be satisfied by a PEP 517 installer`:
when packit/packit#1850 will be closed this should disappear,
in the meantime just drop the warning, which should be solved by the second commit.
> Warnings make packit fail in parsing sandcastle command output

- ogr/factory.py
- tests/unit/test_factory.py
Fixes an issue with project->service mapping where the service with an url not containing the service type wasn't matched.
Related to
Merge before/after
Fixes an issue with project->service mapping where the service with an url not containing the service type wasn't matched.
> Compare hostnames when using custom instances

- ogr/services/gitlab/service.py
- tests/unit/test_factory.py
So users do not need to use any custom mappings to support these. (Especially useful when the mapping is hidden in another tool.)
The list is based on https://wiki.p2pfoundation.net/List_of_Community-Hosted_GitLab_Instances
(Doing a test call to get that automatically would require more work and would result in extra API queries.)
OGR now understands a few community-hosted GitLab instances that could not be determined automatically from the hostname. Thanks to that, you don't need to hardcode these instances to be mapped correctly.
> Add known custom GitLab instances

- .github/workflows/pypi-publish.yml
Passing `--sdist` and `--wheel` makes pypa/build create both from the current source checkout directory. When there's no args passed, though. It first creates an sdist, unpacks it temporarily, and then, creates a wheel out of that sdist source, not Git checkout. This is close to how `pip install` works for installing from sdist, as well as how downstream package stuff.
Adding these CLI options to the PUG guide was a historical mistake I made when writing it.
> Stop building wheel from Git checkout in CI/CD

- LICENSE
- fedora/python-ogr.spec
- tests/integration/pagure/test_project_token.py
```
$ askalono crawl LICENSE
LICENSE
License: MIT (original text)
Score: 1.000
```
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
The changelog should propagate to dist-git as the SPDX migration
initiative tracks 'spdx' string in changelogs.
I'm at the SPDX hackfest right now and the guidance I got about the
LICENSE Copyright line was:
1. it's meaningless and a waste of time to polish
2. only the "copyright" word has a meaning
3. the year is meaningless, hence I dropped it
4. the team name & authors is relevant so I updated it to match 100%
what we have in the source files
> make sure %license is SPDX compatible

- files/tasks/generic-dnf-requirements.yaml
Fixes:
```
[31mCommand 'ansible-playbook --ssh-common-args '-oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oServerAliveInterval=60 -oServerAliveCountMax=5 -oIdentitiesOnly=yes -p22 -i /etc/citool.d/id_rsa_artemis -S/tmp/tmpon0grbsm' -i root@3.128.27.241, /var/ARTIFACTS/git-a4801b0bef6f0b6364115e9e2d8cd8a8906626cbohn_tken/files/packit-testing-farm-prepare.yaml' returned 2.[0m
stdout (16 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PLAY [This is a recipe for preparing the environment when running tests inside testing-farm] ***
TASK [Gathering Facts] *********************************************************
ok: [root@3.128.27.241]
TASK [include_tasks] ***********************************************************
included: …
```
> Remove rpmautospec-rpm-macros from TF playbooks since it's no longer needed

- ogr/services/pagure/project.py
When getting the fork from existing forks, check for equality of the usernames and not only substring check with 'in' operator. This prevents getting a fork of 'packit-stg' for user 'packit'.
Fixes packit/packit-service#2178
We have fixed a bug in `get_fork` method for Pagure about checking the usernames for a match when going through existing forks.
> Fix get_fork for Pagure

- tests/integration/github/test_generic_commands.py
Since version 2.1.0, timestamps in PyGithub are [timezone-aware](https://github.com/PyGithub/PyGithub/commit/0177f7c51327039c8b96b7ebb2731e32b20a8eae).
Remove tzinfo in tests for easy comparison.
Related to https://github.com/packit/requre/pull/275.
> Handle timezone-aware timestamps

- pyproject.toml
It turns out that it's not implicitly included and not having it prevents PyPI upload.
See: https://github.com/packit/ogr/actions/runs/6431356823/job/17464105404#step:6:13
> Add README to package metadata

- ogr/services/gitlab/pull_request.py
- tests/integration/gitlab/test_data/test_pull_requests/PullRequests.test_mr_list_limit.yaml
- tests/integration/gitlab/test_pull_requests.py
TODO:
> python-gitlab==3.14.0
```
Calling a `list()` method without specifying `get_all=True` or
`iterator=True` will return a maximum of 20 items. Your query returned
20 of 87 items.
```
Fixed an issue where getting a list of GitLab merge requests using `.list()` would return only 20 items.
> gitlab list MRs: return all, not just 20

- ogr/services/github/release.py
Change the property so that it returns the html_url of the raw release and not the url which is the API url.
Merge before/after
We have fixed a bug that GithubRelease.url returned an API URL.
> Fix GithubRelease.url to not return API url

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/pagure/project.py
- ogr/services/pagure/pull_request.py
- tests/integration/pagure/test_data/test_pull_requests/PullRequests.test_pr_diff.yaml
- tests/integration/pagure/test_data/test_pull_requests/PullRequests.test_pr_diff_empty_diff.yaml
- tests/integration/pagure/test_pull_requests.py
Needed for packit/packit-service#2271
TODO:
There is a new get_pr_files_diff method supported for Pagure.
> Implement get_pr_diff for Pagure

- ogr/services/pagure/pull_request.py
Ogr debug level strings don't reach Splunk.
> Increase log level in get_files_diff

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/pagure/group.py
- ogr/services/pagure/project.py
- ogr/services/pagure/service.py
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_get_users_with_given_access.yaml
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_pr_permissions.yaml
- tests/integration/pagure/test_data/test_generic_commands/GenericCommands.test_write_access_to_repo.yaml
- tests/integration/pagure/test_data/test_service/Service.test_get_group.yaml
- tests/integration/pagure/test_generic_commands.py
- tests/integration/pagure/test_service.py
Needed for packit/packit#2088
For Pagure there are 2 new methods available: one for getting users with specified access rights and one for getting members of a group.
> Add getting groups and users with given access rights for Pagure

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/github/issue.py
- ogr/services/github/label.py
- ogr/services/github/pull_request.py
- ogr/services/gitlab/issue.py
- ogr/services/gitlab/label.py
- ogr/services/gitlab/pull_request.py
- ogr/services/pagure/issue.py
- ogr/services/pagure/label.py
- ogr/services/pagure/pull_request.py
- tests/integration/gitlab/test_issues.py
- tests/integration/gitlab/test_pull_requests.py
- tests/integration/pagure/test_issues.py
Needed for packit/packit-service#2334
Interface for labels was unified and `labels` property for PullRequest and Issue now return list of PRLabel and IssueLabel respectively.
> Unify interface for labels

- ogr/services/gitlab/project.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_file_content_resolve_dot.yaml
- tests/integration/gitlab/test_generic_commands.py
So that the behaviour is consistent among forges. GitLab cannot do this automatically (confirmed that both GitHub and Pagure can).
Related to #838
`GitLabProject.get_file_content` can now correctly handle file paths starting with `./`.
> Remove ./ when getting file in GitLab

- .pre-commit-config.yaml
- plans/packit-integration.fmf
> Avoid deepdiff version 8.0.0 in packit tests

- .pre-commit-config.yaml
- examples/list_prs_since_release.ipynb
- examples/releases.ipynb
- examples/syncing_labels.ipynb
- examples/user_owned_repositories.ipynb
- ogr/services/github/project.py
- tests/integration/github/test_generic_commands.py
- tests/unit/test_github.py
- tests/unit/test_utils.py
Remove the unreachable ‹except› block. Since the ‹collaborators› is populated from a helper method that can produce only exceptions that are wrapped in the ogr's exceptions (handled by the metaclass), hence the ‹github.GithubException› cannot be raised.
Fixes #760
> fix: remove unreachable exception handling

- COMPATIBILITY.md
- ogr/abstract.py
- ogr/services/github/project.py
- ogr/services/gitlab/project.py
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_commits.yaml
- tests/integration/gitlab/test_generic_commands.py
Related to https://github.com/packit/packit-service/issues/2495.
> Implement `GitProject.get_commits()`

- ogr/services/github/service.py
- tests/unit/test_factory.py
Should partially fix packit/packit-service#2512
> Fixes related with packit service slowliness

- ogr/abstract.py
- ogr/read_only.py
- ogr/services/github/comments.py
- ogr/services/github/project.py
- ogr/services/gitlab/comments.py
- ogr/services/gitlab/project.py
- ogr/services/pagure/project.py
- tests/integration/github/test_data/test_generic_commands/GenericCommands.test_get_commit_comment.yaml
- tests/integration/github/test_generic_commands.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_commit_comment.yaml
- tests/integration/gitlab/test_generic_commands.py
Make the CommitComment inherit from Comment directly to share the common functionality (e.g. adding emojis).
Needed for packit/packit-service#2589
There is a new method for getting a single commit comment, supporting also retrieval and adding reactions in GitHub.
> Implement get_commit_comment method and refactor CommitComment

- fedora/python-ogr.spec
- plans/packit-integration.fmf
Sync of downstream change: https://src.fedoraproject.org/rpms/python-ogr/pull-request/688
> Remove outdated EPEL 9 workaround

- .packit.yaml
- ogr/__init__.py
- ogr/abstract.py
- ogr/exceptions.py
- ogr/services/forgejo/__init__.py
- ogr/services/forgejo/issue.py
- ogr/services/forgejo/project.py
- ogr/services/forgejo/pull_request.py
- ogr/services/forgejo/service.py
- ogr/services/forgejo/user.py
- pyproject.toml
- tests/integration/factory/test_data/test_factory/FactoryTests.test_get_project_forgejo.yaml
- tests/integration/factory/test_factory.py
- tests/integration/forgejo/README.md
- tests/integration/forgejo/__init__.py
- tests/integration/forgejo/conftest.py
- tests/integration/forgejo/test_data/test_service/test_project_create.yaml
- tests/integration/forgejo/test_service.py
> Add base support for forgejo

- .packit.yaml
> Build ogr just for stable releases

- ogr/services/gitlab/project.py
- tests/integration/gitlab/test_data/test_generic_commands/GenericCommands.test_get_commit_comments.yaml
TODO:
Fixes #894 
We have fixed pagination problems in ogr's `GitlabProject.get_commit_comments()`.
> fix pagination problem in commit comments[gitlab]

- plans/packit-integration.fmf
Discovered by @nforro that we do not run ‹session-recording› tests during the reverse-dependency testing in ogr. However when I tried to enable it, I hit other issues that stem from pulling in additional dependencies for the ‹full› test suite when running together with ‹session-recording›.
Since my changes in Packit involve changes of tiers of tests, we need to explicitly specify that we want to run only the ‹tag:full›, so skip the ‹session-recording› for now anyways as running everything breaks…
I will try to set up importing of the plans which could resolve this… If you do not see the commit that resolves this via importing of plans, my plan has failed :)
---
Fixes CI in #918
> ci(tmt): run only full test suite for rev-dep

- COMPATIBILITY.md
- CONTRIBUTING.md
- Makefile
- ogr/services/forgejo/project.py
- tests/integration/forgejo/test_data/test_project/test_add_remove_user.yaml
- tests/integration/forgejo/test_data/test_project/test_get_contributors.yaml
- tests/integration/forgejo/test_data/test_project/test_get_owners.yaml
- tests/integration/forgejo/test_data/test_project/test_get_users_with_given_access.yaml
- tests/integration/forgejo/test_data/test_project/test_issue_permissions.yaml
- tests/integration/forgejo/test_data/test_project/test_pr_permissions.yaml
- tests/integration/forgejo/test_project.py
TODO:
Fixes #878
We have added support for Forgejo methods related to permissions.
> Forgejo permissions
